### ISSUE TITLE
Step by Step guide on how to use Mule-lint

### ISSUE THREAD

**Issue by sumit-b02** [mule-lint/mule-lint#13]
Requirement : I want to use Mule lint for static analysis of the mule code. By static analysis i mean, there are some best coding practices across the organisation which i want to check for every mule integration project that is built. I need to automate this process of Code Review. I came across Sonar XML path rules, but XML path 1.0 has several limitations, hence discarded. Next i came across Mule lint found it interesting. But as a noob, i don't know how to use this mule lint for a demo project of mine. I am raising this to get me a step by step guide on how to use this and make it universal for any future project of my organisation.

Thanks,
Sumit

**Comment by sumit-b02** [comment]
@cgorshing - request your help here.

**Comment by cgorshing** [comment]
I will work on putting something together and posting it here. Stay tuned!

**Comment by sumit-b02** [comment]
Thank you @cgorshing  Eagerly waiting for a response.

**Comment by aashmaharoon** [comment]
Hi @cgorshing , 
Any update on this plugin. I also tried the tag 4 version because the master branch build fails. Anyway, I tried to use rules which you have mentioned as examples. Only 'has attributes' works and whenever other syntax used, maven build fails with "not emplemented" error. Can you please provide any workable sample rule set please?

**Comment by cgorshing** [comment]
Yes @sumit-b02 and @aashmaharoon - My apologies on this. This week. Promise.

**Comment by cgorshing** [comment]
I've updated this project's README.md to link to https://github.com/Nuisto/example-mule-lint-project showing how the rules.txt is setup and running `mvn clean compile`

If that example project does not help, then let me know what you were confused on or what wasn't clear.

I would be interested in what you all are planning to do with the `results.json` output file.
