### ISSUE TITLE
Any plans for mule 4.x support/example project?

### ISSUE THREAD

**Issue by christiaanhoogendoornvopak** [mule-lint/mule-lint#21]
Hi,

Are there any plans for mule 4.x support? Or if this is already possible a working example project for mule 4.x?

Chris

**Comment by cgorshing** [comment]
Absolutely! I haven't had the opportunity to work on a Mule4 project [yet], but I will work with others to ensure all is functioning correctly for Mule4.

I'm sure new rules will come out of it as well.

**Comment by christiaanhoogendoornvopak** [comment]
That is great news? Do you have any idea of a timefrime when this can be expected?

Chris

**Comment by christiaanhoogendoornvopak** [comment]
I found out this actually this is very simple to fix by changing the maven plugin configuration to 					<sources>src/main/mule</sources> since in mule 4 the Mule Flows are in the mule folder rather than in src/main/app.
