### ISSUE TITLE
how to apply rules on both mule flows and munit folders?

### ISSUE THREAD

**Issue by christiaanhoogendoornvopak** [mule-lint/mule-lint#23]
Hello,

We have the same naming conventions for Munt and Mule flows. How can I pass in the 2 folders both into the maven plugin?

This configuration in the pom.xml (using the maven plugin) does not work (yet) 
<sources>src/main/app, src/test/munit</sources>

thank you!

Christiaan

p.s. using 0.5.1

**Comment by cgorshing** [comment]
I would just use `src`. There is an exclude option in case there are flow you need to exclude as well.

**Comment by christiaanhoogendoornvopak** [comment]
great, works. Thanks!
