### ISSUE TITLE
check contents of pom file?

### ISSUE THREAD

**Issue by christiaanhoogendoornvopak** [mule-lint/mule-lint#24]
Hello,

Does mule-lint already or ever will (also) support functionality to :
- validate if certain versions of maven dependencies are present in the pom.xml? (to detect if depricated versions are still being used or if the latest parent pom is used)

Christiaan

**Comment by cgorshing** [comment]
I hadn't thought about adding this in, I would think there are already solutions for handling maven dependency issues. But if there isn't something like this, then I'm sure something can be put together.

What dependencies would be an issue to help protect against?

**Comment by christiaanhoogendoornvopak** [comment]
I will first investigate other solutions like you suggest, and later come back with potential improvements.

Thank you!

Christiaan
