### ISSUE TITLE
check contents of yaml files? 

### ISSUE THREAD

**Issue by christiaanhoogendoornvopak** [mule-lint/mule-lint#25]
Is there an option to check contents of yaml files?

for instance:
- if a property in a yaml file is named ´password´ it must be encrypted?
- if a property in a yaml file contains 'queue' it must only contain lower case and be dot-seperated?

thank you!

Christiaan

**Comment by cgorshing** [comment]
One thing that makes Mule code easier to process is the format is well known, besides xml, there is also a schema for it. How would this work for yaml files? Would a `password` attribute be at any level or just the root level?

**Comment by christiaanhoogendoornvopak** [comment]
At any level.  A yaml file has some quite strict formatting rules and hierarchy, but there is no schema for it as such. There is no single root element like xml, but you will be able to create an in memory tree and search for certain words (perhaps in a dictionary) and verify that the actual value starts with ![ and ends with ], indicating that it is encrypted.

Attached is an  example raml file (rename to yaml, github does not support .yaml extension). Note that all sibblings within a parent have to be at the exact same indentation inside their parent.

[example.yaml.txt](https://github.com/mule-lint/mule-lint/files/3701340/example.yaml.txt)

**Comment by cgorshing** [comment]
I'm struggling to keep the scope of this project moving, so I'm going to try and stay focused on what to do next. For yaml, I can easily see that be valuable, but possibly for another project. Closing for now, but happy to discuss later if mule-lint continues to grow.
