### ISSUE TITLE
Question : mule-lint & maven plugin generation

### ISSUE THREAD

**Issue by Boudedi** [mule-lint/mule-lint#27]
Hi @cgorshing, 
I am testing mule-lint and finding very it interesting. 
I am wondering how to generate the mule-lint-maven-plugin based on a current project.
Are there any particular steps?

Thank you, I would love to contribute to this project.

**Comment by cgorshing** [comment]
I'm not sure what you mean by "generate" ... The maven plugin is a different project and has some instructions on what changes need to be made to your existing pom/project. I also made https://github.com/mule-lint/example-mule-lint-project which will show you what a pom could look like with the maven plugin.
