### ISSUE TITLE
What does the dictionary.txt do and how should I use it?

### ISSUE THREAD

**Issue by christiaanhoogendoornvopak** [mule-lint/mule-lint#28]
Hi,

I cannot find the exact purpose of the dictionary.txt file. How can we use it to our advantage? Can you describe a short usecase (or a how-to) how it can be beneficial?

Christiaan

**Comment by cgorshing** [comment]
Good call out - The best I have is at https://github.com/mule-lint/mule-lint/wiki/Handling-of-Camel-and-Pascal-Case .. but still doesn't call it out explicitly. I'll work on this.

**Comment by cgorshing** [comment]
I added some docs to https://github.com/mule-lint/mule-lint/wiki/Configuration - I still need to do more, but this is a start.
