### ISSUE TITLE
Building master branch in my local box

### ISSUE THREAD

**Issue by AppBankDigital** [mule-lint/mule-lint#31]
when i try to run ./gradlew build in my local machine and getting the below error. JDK 1-.8 in my machine and used master branch code.

* What went wrong:
A problem occurred evaluating root project 'mule-lint'.
> Could not get unknown property 'ossrhUsername' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

**Comment by cgorshing** [comment]
Thank you for this - I haven't had anybody else build it besides me. This error, and others you will run into, are related to the `maven` and `signing` gradle plugins. I'm looking to see what options exist to work around this so others can build without having to have these properties defined/used. I'll let you know what I find out.

For now, if you are interested, you should be able to create a file named `grade.properties` in the projects root directory with:

    signing.keyId=
    signing.password=
    signing.secretKeyRingFile=<HOME>/.gnupg/secring.gpg

    ossrhUsername=
    ossrhPassword=

**Comment by AppBankDigital** [comment]
Thanks for the reply. The signing step is not working. Is there any easy option to handle this.


************************************
> Task :signArchives FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signArchives'.
> the key id 'ail.com>' is not a valid hex string

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 541ms
6 actionable tasks: 1 executed, 5 up-to-date

**Comment by cgorshing** [comment]
You can probably remove the maven and signing plugin along with the config for those plugins (so you don't get undefined errors). I'm looking at how to make this optional, I'm not sure what options are available for these plugins so I'm looking through that.

**Comment by cgorshing** [comment]
Pull and try again please - I just pushed up some changes that _might_ make `./gradlew build` work now :)

**Comment by prapakaransp** [comment]
Let me check and keep you posted.

**Comment by cgorshing** [comment]
(Correction) Now try it 👍 

I found another issue with the username/password even though the task doesn't execute.

Above I mentioned doing a `./gradlew build` but try a `./gradlew install` as that is more what you are wanting to do I'm sure.
