### ISSUE TITLE
requesting rules to add

### ISSUE THREAD

**Issue by ptupakul** [mule-lint/mule-lint#33]
HI,

I am Using Mule lint for my mule application code review purpose. But I am able to only few rules that you are mentioned in example project..
some rules to implement like..
1). Mule configuration file Naming convention checking..
2). Property files existed or not in the project..
3).Unable to check naming convention for most of the components having attribute "doc:name"(because of colon)....

**Comment by cgorshing** [comment]
Thanks for the feedback, questions for ya.

1) What conventions would you like to start with? Just casing conventions?
2) For the property files check, how would this list be given to mule-lint? Or would it be sourced from other files?
3) let me check on the "doc:name" attribute.

**Comment by ptupakul** [comment]
Hi,

1.Just casing conventions?--> yes.(mostly kebab case) and also try to implement  casing checking for all components.. if possible
2. for property files if it possible take it from the src/main/resources.. check suffix like ${mule.env} .**properties** or ${mule.env}.**yaml**..  
3. **hasChild** is also giving problem please look into that. then we can write more rules.

**Comment by ptupakul** [comment]
Can we check Naming conventions Using Regular expressions ??..

**Comment by goelmayank** [comment]
hi,

can we add this rule: 'json-to-object-transformmer' hasParent 'dw:transgorm-message'

**Comment by cgorshing** [comment]
@goelmayank Do you really mean parent or preceding sibling? Can you provide a code example?

@ptupakul Let me see what regex's would be like.

Also FYI - Mule has a sonarqube plugin now https://www.linkedin.com/pulse/mulesoft-sonar-plugin-mule4-mule3-sadik-ali

**Comment by goelmayank** [comment]
@cgorshing yes, I mean preceding sibling. rule: 'json-to-object-transformmer' hasPrecedingSibling 'dw:transform-message'

**Comment by goelmayank** [comment]
ok I just found that hasPriorSibling and hasFollowingSibling is already there and it works for any tags

**Comment by goelmayank** [comment]
@cgorshing, I have a few more requirements. Could you kindly throw more clarity on whether we can modify the utility to:
1. check for hardcoded values for certain tags like <add-message-property>, 
2. check if a certain attribute of a certain tag has a value different from the specified one, 
3. check if any of the child tags of an element have repeated key values.

**Comment by cgorshing** [comment]
@goelmayank For 1, I would need more information, open a new issue with those details.

2 - this has been on my mind as well.

3 - Can you open a new issue and provide some code examples of what you are thinking?

**Comment by goelmayank** [comment]
Hi @cgorshing, I have opened up 4 issues as requested by you. 34, 35, 36, and 37. Kindly have a look and let me know if we can customize the utility on our end.

**Comment by cgorshing** [comment]
@ptupakul You are correct about doc:name, I'll work up a test case and get that fixed, thank you for reporting that!

**Comment by cgorshing** [comment]
@ptupakul Can you give me more information of "hasChild is also giving problem please look into that. then we can write more rules." please. An example rule or flow would be good

**Comment by cgorshing** [comment]
@goelmayank  "check if a certain attribute of a certain tag has a value different from the specified one". Can you try a rule such as:

    element 'dw:transform-message' hasAttribute 'something', ['expected attribute', 'or another possible one']

I don't like the above syntax, but it is working for me, at least for the test I have written up. If something isn't working for you, then please open a new issue with some additional details.

**Comment by goelmayank** [comment]
@cgorshing Right now what it does is it give me a message for all the times the node does not have that attribute as well. My requirement is that when I specify this rule to check value for a certain attribute in a node, I get a message in results.json only when that attribute is present in the node.

E.g. 
<set-attribute key1="valueA">ABC</set-attribute>
<set-attribute key2="valueB">ABC</set-attribute>

Rule : element 'set-attribute' hasAttribute 'key1', ['valueA']

In the result, we also get:

element 'set-attribute' does not have attribute key1 

On a side note, if we can also have a regex check so that we can check for things like if it has been hardcoded or taking value from a variable.

**Comment by cgorshing** [comment]
I'm going to close this issue for now. There are many different items being discussed and I'm all for continuing the conversation in specific stories for each item. Having this one issue open for numerous requests isn't the best way to move forward.

I'll look at what it would take to get regex matching or kabab casing in the rules.
