### ISSUE TITLE
Requesting rules to check for hardcoded values for mule tags

### ISSUE THREAD

**Issue by goelmayank** [mule-lint/mule-lint#34]
The way to distinguish between hardcoded and non hardcoded values for mule tags is by checking for the presence of certain specific characters. Generally, if a variable is present in the value, it will start with a $ symbol and if it is a hard-coded value, it would begin with anything other than a $ symbol.

Example of a hardcoded value:

<add-message-property key="Saml" value="&lt;saml:Assertion ...>

Example of a non hardcoded value:

<add-message-property key="Saml" value="${saml} ...>

**Comment by cgorshing** [comment]
Would you want the rule to fail if it is hardcoded?

Would you want it tied to a specific element or in general? Meaning a rule for "all elements should not have a hard coded attribute"?

Some api related mule code has flow names as `get-business-units-{buCode}-inventory-{sku}` would these fail the hardcoded rule or would they pass? Would attributes as "prefix-value-${blah}" be acceptable? Meaning the rule would not fail/trigger.

**Comment by goelmayank** [comment]
@cgorshing I will like to have it work for a specific element. 

get-business-units-{buCode}-inventory-{sku} is hard coded so it should fail. not hard coded means ${...} syntax.
