### ISSUE TITLE
Rule to check if a certain attribute of a certain tag has a value different from the specified one

### ISSUE THREAD

**Issue by goelmayank** [mule-lint/mule-lint#35]
I think it is obvious and needs no example.

**Comment by cgorshing** [comment]
@goelmayank You have mentioned this in #33 as well. I've tried a couple different combinations and can't get it to fail. What version are you using? It may be obvious to you, but can you provide an example rule and mule flow snippet to repro please as I am not able to now.

**Comment by goelmayank** [comment]
@cgorshing Right now what it does is it give me a message for all the times the node does not have that attribute as well. My requirement is that when I specify this rule to check value for a certain attribute in a node, I get a message in results.json only when that attribute is present in the node.

E.g.
Line 1. <node attritbute1="value1" />
Line 2. <node attritbute2="value2" />

Rule : element 'node' hasAttribute ('attritbute1', ['value1'])

In the result, we also get:

element 'node' does not have attribute attritbute1 for Line 2.

Since majority of the nodes are not having the attribute, it is giving many extraneous logs right now. Is there a way to make sure that when we are checking value, only value is checked and not attribute.

**Comment by cgorshing** [comment]
@goelmayank I'm not able to reproduce this. If you could provide some example information (flow, elements, rules, and results file) that would be great.

Mule flow example I'm using
```
<mule xmlns:dw="http://www.mulesoft.org/schema/mule/ee/dw" xmlns:metadata="http://www.mulesoft.org/schema/mule/metadata" xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns:tracking="http://www.mulesoft.org/schema/mule/ee/tracking" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:spring="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/ee/tracking http://www.mulesoft.org/schema/mule/ee/tracking/current/mule-tracking-ee.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/dw http://www.mulesoft.org/schema/mule/ee/dw/current/dw.xsd">

    <flow name="updatePlanStatus" processingStrategy="synchronous">
        <logger message="flow=updatePlanStatus action=started messageId=#[message.id] projectId=#[flowVars.projectId]" level="INFO" category="com.acme.logging.plan" doc:name="Logger"/>

        <dw:transform-message doc:name="Transform Message" metadata:id="50a69c4e-dacb-46f1-b0f0-bbaae64649fd">
            <dw:set-payload><![CDATA[%dw 1.0
%output application/xml
---
//Some example DW Transform
{
}
]]></dw:set-payload>
        </dw:transform-message>

        <http:request config-ref="Request_Configuration" path="/some/path" method="POST" doc:name="Update Plan">
            <http:request-builder>
                <http:header headerName="User-Agent" value="UserAgentName 0.1 (Project Name)"/>
            </http:request-builder>
        </http:request>

        <node attribute1="value1"/>
    </flow>
</mule>
```

The rules file:
```
version '0.0.1'

element 'node' hasAttribute 'attribute1', ['value1']
```

And the results file:
```
{
    "version": "0.0.2",
    "findings": [
        
    ]
}
```

When mule-lint rules, I also get the output that it found no infractions:
```
[main] INFO org.nuisto.msa - Found 2 files
[main] INFO org.nuisto.msa - Found 0 infractions.
```

**Comment by goelmayank** [comment]
Hi @cgorshing i meant if there is a node which does not have attribute1 as an attribute, then it will print in log, that node does not have attribute1 as an attribute but the purpose of the rule is to check if the value In attribute1 is value1 or not, not to check if attribute1 itself is there or not.

**Comment by cgorshing** [comment]
"but the purpose of the rule is to check if the value In attribute1 is value1 or not, not to check if attribute1 itself is there or not" that is incorrect, the purpose of the rule is that the attribute is there **AND** with the value. I'll change the wording to make that more clear.

This is working as intended, just the messaging isn't clear.
