### ISSUE TITLE
Rule to check if any of the child tags of an element have repeated key values

### ISSUE THREAD

**Issue by goelmayank** [mule-lint/mule-lint#36]
Example of repeated child tags of an element:

<message-properties-transformer name="parentVariable" doc:name="accountsListOutboundHeadersForEntitlementsDecisions" >
            <add-message-property key="variable1" value="value1"/>
            <add-message-property key="variable2" value="value2"/>
            <add-message-property key="variable1" value="value1"/>
</message-properties-transformer>

**Comment by goelmayank** [comment]
<message-properties-transformer name="parentVariable" doc:name="accountsListOutboundHeadersForEntitlementsDecisions" >
            <add-message-property key="variable1" value="value1"/>
            <add-message-property key="variable2" value="value2"/>
            <add-message-property key="variable1" value="value1"/>
</message-properties-transformer>

**Comment by cgorshing** [comment]
@goelmayank Can you try to update your message above please so your example is shown - thanks!

**Comment by goelmayank** [comment]
```
<message-properties-transformer name="parentVariable" doc:name="accountsListOutboundHeadersForEntitlementsDecisions" >
            <add-message-property key1="value1" />
            <add-message-property key2="value2" />
            <add-message-property key1="value1" />
            <add-message-property key2="value1" />
</message-properties-transformer>

Here for same keys (key1 and key2) in node, value is being assigned twice withing the same node which should throw an exception.
```
