### ISSUE TITLE
Rule to check if transformation component is used to set variables instead of set variable component

### ISSUE THREAD

**Issue by goelmayank** [mule-lint/mule-lint#37]
One can create, or update, variables in these ways:

1. Using the Set Variable component.
2. Using the DataWeave Transform Component (EE-Only)

Mule guidelines discourage the use of a Transform Component to set a variable in cases such as selections and instead recommend the use of the Set Variable component in such cases.

This XML example sets a variable that takes a map as a value: 
<set-variable variableName="employee" value="{ 'name' : 'Ana', 'office' : 'BA' }" mimeType="application/json" encoding="UTF-8/>

This example sets the same variable using selectors in a DataWeave script. It assumes the name attribute is available as input to Set Variable: 
<set-variable variableName="employee" value="#[output application/java --- payload.name]"/>

**Comment by cgorshing** [comment]
@goelmayank Did you get cut off? I'm not seeing an ask above.

**Comment by cgorshing** [comment]
@goelmayank I'm closing this for now, if you can provide more details I could re-open. I agree there is a lot that can be done around variables and dataweave particularly.
