### ISSUE TITLE
Is it possible to build mule lint with maven

### ISSUE THREAD

**Issue by goelmayank** [mule-lint/mule-lint#39]
Hi @cgorshing In my organization, Gradle is not supported so I am facing issues with build the mule-lint project in my office laptop. Using the Spring tool suite, I was able to convert the mule-lint project into a maven project. But then mule-lint-maven-plugin failed to build with the jar file of the mule-lint project thus built. Is there a way to build mule-lint using maven. ALso if it is possible, shouldn't we be able to sskip the mule-lint maven plugin altogether.

**Comment by cgorshing** [comment]
For your work, why would you need to build mule-lint?

I plan on keeping it as a Gradle project and as a separate jar file so we can possibly use it in other environments (either Sonarqube, Eclipse/Intellij plugin, build server integration ..etc).
