### ISSUE TITLE
Estimate on timeline for new rules

### ISSUE THREAD

**Issue by goelmayank** [mule-lint/mule-lint#40]
hi @cgorshing,

I came across these rules in your test/resources/rules.txt

`
element 'logger' hasMatchingAttribute 'category', 'com.example.*'
element 'logger' hasAttributeStartingWith 'category', 'com.example'
element 'logger' hasAttribute 'category' startingWith 'com.example'

//Version number to be determined
//element 'http:request' hasChild 'User-Agent'

//element 'http:request' hasChild 'http:header' withAttribute 'headerName' havingValue 'User-Agent' withAttribute 'value' havingValue 'my-bot-name 1.0'
`

Kindly inform me about your plans for their implementation.

**Comment by cgorshing** [comment]
I'm working on some new rules, once I get those lined out I'll get back to you on this one.

**Comment by cgorshing** [comment]
I'm working these into the new rules. I've got `valueMatching` working with the new rules. I'm working on the documentation.

https://github.com/mule-lint/mule-lint/commit/a27c7a861c3e7ab0e0eaf1552f1d4bf570244bb7
