### ISSUE TITLE
Rule in readme not working

### ISSUE THREAD

**Issue by goelmayank** [mule-lint/mule-lint#41]
Hi @cgorshing  themule-lint rule with multiple values in hasAttribute is not working.

**Comment by cgorshing** [comment]
Thanks for reporting it

Are you talking about this one:

    element 'http:request' hasChild 'http:header' withAttribute 'headerName' havingValue 'User-Agent' withAttribute 'value' havingValue 'my-bot-name 1.0'

**Comment by cgorshing** [comment]
Closing for now - let me know if you can provide a bit more information.
