### ISSUE TITLE
Request for new rules

### ISSUE THREAD

**Issue by mayankhsbc** [mule-lint/mule-lint#42]
1. Outbound headers should not be duplicated to SAPI calls  --- Pending

 

We can check whether any key or value attribute is having duplicate value or not

 

For Example -

 

<add-message-property key="Cache-Control" value="no-cache"/>

<add-message-property key="Cache-Control" value="no-cache"/>

 

For Value attribute, I think our existing below rule Should work. But need to have single rule for both key and value attributes.

 

element 'add-message-property' hasAttribute ('value', ['${','#['])

2. Backend Retry should be done only for HTTP methods which are both SAFE and IDEMPOTENT ( GET calls) and 'http:request' should have Parent as 'until-successful'

 

element 'http:request' hasAttribute ('method', 'GET') hasParent 'until-successful' --- This rule should work  -- Pending

 

Example -

 

<until-successful maxRetries="${sapi.max.retries}" millisBetweenRetries="${sapi.retries.interval}" synchronous="true" doc:name="Until Successful">

            <http:request config-ref="SAPI-HTTP-Customer-Bands-Charges" path="/users/customer-bands" method="GET" doc:name="HTTP">

            </http:request>

        </until-successful>

 

                            

 

3. Use Else statement(empty atleast)  alongwith If statement inside For Each block.

 

element 'expression-component' hasAttribute ('![CDATA', ['if(','}else{']) -- Need rule for this  --- Pending

 

else statement should be there in for each. if it is not there then it should come in result.json file

 

Example --

 

<foreach  collection="bandDataVar" doc:name="For Each">

                                           <expression-component doc:name="Date Range Expression"><![CDATA[

                                           if(flowVars.bandDataVar[counter-1].bandType.equals("FX"))

                                           {

                                                          flowVars.bandToClientId = flowVars.bandDataVar[counter-1].bandNumberFXM;

                                                         

                                           }

                                           else

                                           {

                                           // nothing

                                           }

                                           ]]>

                                           </expression-component>

            <logger level="INFO" doc:name="Logger"/>

                                          

                             </foreach>

**Comment by cgorshing** [comment]
I'm currently working through some new rules and figuring out how they will fit. I'll get back to you soon

**Comment by goelmayank** [comment]
@cgorshing would you mind sharing by when and what can we expect in the update so that I can plan accordingly.

**Comment by cgorshing** [comment]
I was without power for over a week due to a winter storm that has slowed me down and impact other areas. My plan is to leave the current format of the rules alone, but I'm building out a new way to describe the rules entirely. The rules are growing too much for a nice little sentence. I looked at using multiple sentences to pair things together, but then I have to carry start across and had some other troubles. More to come, I'm hoping for another week or so.

**Comment by cgorshing** [comment]
@mayankhsbc Is the first one you describe the same as https://github.com/mule-lint/mule-lint/issues/36?

For your second request - I've seen folks have a http post in a loop of 3 times if the error code is a 500. They were dealing with a http service that wasn't too reliable and would often return 500's. Typically I agree with you, but I'm not sure I want to have that as a rule.

For your third request - Can you elaborate on what you mean by `else statement should be there in for each`, I'm not understanding what you are wanting.

**Comment by goelmayank** [comment]
@cgorshing I had been travelling so sorry for the delay in reply. Yes. They are the same..

Any idea if we will be having these rules anytime soon or how we can go about implementing them ?

**Comment by cgorshing** [comment]
If you are talking about the rules "mayankhsbc" requested (which I guess is your second account), then I still have questions you haven't answered above.

**Comment by goelmayank** [comment]
@cgorshing I don't know how I missed out your questions.

For the second request, I agree that the rule as is may not be in need universally but you will agree that there should be a provision to have a rule to simultaneously check for the presence of more than 1 property on a node, in this case, the two properties being that the value attribute has value of http and the hasParent check for checking if until-succesful block is present.

For the third rule, for each is a block we can pick from the mule pallete and it allows us to specify if else conditions. The requirement is to ensure that if that if else both are present and not just an if condition.
